Slitherlink Solver: slitherlink::SlitherlinkAPI Class Reference
slitherlink::SlitherlinkAPI Class Reference
#include <Slitherlink.h>
Static Public Member Functions
static std::vector< Solution > solve (const std::string &filename, const SolverConfig &config=SolverConfig::defaults())
static std::vector< Solution > solve (const Grid &grid, const SolverConfig &config=SolverConfig::defaults())
Detailed Description
Definition at line 30 of file Slitherlink.h.
Member Function Documentation
solve() [1/2]
std::vector< Solution > slitherlink::SlitherlinkAPI::solve (const Grid & grid, const SolverConfig & config = SolverConfig::defaults()) inline static
Definition at line 41 of file Slitherlink.h.
References slitherlink::SolverFactory::createSolver(), and slitherlink::SolverConfig::defaults().
solve() [2/2]
std::vector< Solution > slitherlink::SlitherlinkAPI::solve (const std::string & filename, const SolverConfig & config = SolverConfig::defaults()) inline static
Definition at line 33 of file Slitherlink.h.
References slitherlink::SolverFactory::createSolver(), and slitherlink::SolverConfig::defaults().
The documentation for this class was generated from the following file:
include/slitherlink/Slitherlink.h