Slitherlink Solver: Solver Struct Reference
Solver Struct Reference
Public Member Functions
int calculateOptimalParallelDepth ()
void buildEdges ()
State initialState () const
bool applyDecision (State &s, int edgeIdx, int val) const
Apply edge decision and update state (#13 - inlined hot path).
bool quickValidityCheck (const State &s) const
Quick validity check (#13 - inlined hot path).
bool propagateConstraints (State &s) const
int estimateBranches (const State &s, int edgeIdx) const
Estimate branching factor for an edge decision (#11).
int selectNextEdge (const State &s) const
Select next edge using smart heuristics (#11).
bool finalCheckAndStore (State &s)
bool testEdgeDecision (const State &s, int edgeIdx, int val) const
Look-ahead pruning (#12) - Test if edge decision leads to valid state.
bool isCanonicalSolution (const Solution &sol) const
Symmetry breaking (#9) - Check if solution is in canonical form.
bool isDefinitelyUnsolvable (const State &s) const
Early detection of definitely unsolvable states.
void search (State s, int depth)
void run (bool allSolutions, int numThreads=0, double cpuPercent=1.0)
void printSolution (const Solution &sol) const
void printSolutions () const
Public Attributes
Grid grid
vector< Edge > edges
int numPoints = 0
vector< int > horizEdgeIndex
vector< int > vertEdgeIndex
vector< vector< int > > cellEdges
vector< vector< int > > pointEdges
vector< int > clueCells
bool findAll = false
atomic< bool > stopAfterFirst {false}
mutex solMutex
vector< Solution > solutions
atomic< int > solutionCount {0}
int maxParallelDepth = 16
atomic< int > activeThreads {0}
int maxThreads = thread::hardware_concurrency() > 0 ? thread::hardware_concurrency() : 4
unique_ptr< tbb::task_arena > arena
tbb::concurrent_vector< Solution > tbbSolutions
Detailed Description
Definition at line 166 of file main.cpp.
Member Function Documentation
applyDecision()
bool Solver::applyDecision (State & s, int edgeIdx, int val) const inline
Apply edge decision and update state (#13 - inlined hot path).
Definition at line 300 of file main.cpp.
References Edge::cellA, Edge::cellB, State::cellEdgeCount, State::cellUndecided, edges, State::edgeState, grid, State::pointDegree, State::pointUndecided, Edge::u, and Edge::v.
Referenced by propagateConstraints(), search(), and testEdgeDecision().
buildEdges()
void Solver::buildEdges () inline
Definition at line 213 of file main.cpp.
References Edge::cellA, Edge::cellB, cellEdges, clueCells, edges, grid, horizEdgeIndex, numPoints, pointEdges, Edge::u, Edge::v, and vertEdgeIndex.
Referenced by run().
calculateOptimalParallelDepth()
int Solver::calculateOptimalParallelDepth () inline
Definition at line 194 of file main.cpp.
References grid.
Referenced by run().
estimateBranches()
int Solver::estimateBranches (const State & s, int edgeIdx) const inline
Estimate branching factor for an edge decision (#11).
Tests both ON and OFF decisions with quick validity checks. Returns number of viable branches (0, 1, or 2).
Definition at line 594 of file main.cpp.
References edges, State::pointDegree, State::pointUndecided, Edge::u, and Edge::v.
Referenced by selectNextEdge().
finalCheckAndStore()
bool Solver::finalCheckAndStore (State & s) inline
Definition at line 668 of file main.cpp.
References State::cellEdgeCount, clueCells, edges, grid, numPoints, and State::pointDegree.
Referenced by search().
initialState()
State Solver::initialState () const inline
Definition at line 270 of file main.cpp.
References State::cellEdgeCount, cellEdges, State::cellUndecided, edges, State::edgeState, grid, numPoints, State::pointDegree, pointEdges, and State::pointUndecided.
Referenced by run().
isCanonicalSolution()
bool Solver::isCanonicalSolution (const Solution & sol) const inline
Symmetry breaking (#9) - Check if solution is in canonical form.
For findAll mode, eliminates symmetric duplicates by checking if this is the lexicographically smallest rotation/reflection.
Definition at line 900 of file main.cpp.
References Solution::edgeState, findAll, grid, and horizEdgeIndex.
isDefinitelyUnsolvable()
bool Solver::isDefinitelyUnsolvable (const State & s) const inline
Early detection of definitely unsolvable states.
Quickly checks for conditions that make a state impossible to solve, allowing early termination without full propagation.
Parameters
s Current state to check
Returns
true if state is definitely unsolvable, false otherwise
Definition at line 941 of file main.cpp.
References State::cellEdgeCount, State::cellUndecided, clueCells, grid, numPoints, State::pointDegree, and State::pointUndecided.
Referenced by search().
printSolution()
void Solver::printSolution (const Solution & sol) const inline
Definition at line 1176 of file main.cpp.
References Solution::cyclePoints, Solution::edgeState, grid, horizEdgeIndex, and vertEdgeIndex.
printSolutions()
void Solver::printSolutions () const inline
Definition at line 1229 of file main.cpp.
References solutions.
Referenced by main().
propagateConstraints()
bool Solver::propagateConstraints (State & s) const inline
Definition at line 407 of file main.cpp.
References applyDecision(), Edge::cellA, Edge::cellB, State::cellEdgeCount, cellEdges, State::cellUndecided, clueCells, edges, State::edgeState, grid, numPoints, State::pointDegree, pointEdges, State::pointUndecided, Edge::u, and Edge::v.
Referenced by search(), and testEdgeDecision().
quickValidityCheck()
bool Solver::quickValidityCheck (const State & s) const inline
Quick validity check (#13 - inlined hot path).
Definition at line 343 of file main.cpp.
References clueCells, numPoints, State::pointDegree, and State::pointUndecided.
Referenced by search().
run()
void Solver::run (bool allSolutions, int numThreads = 0, double cpuPercent = 1.0) inline
Definition at line 1124 of file main.cpp.
References arena, buildEdges(), calculateOptimalParallelDepth(), findAll, grid, initialState(), maxParallelDepth, maxThreads, search(), solutionCount, solutions, stopAfterFirst, and tbbSolutions.
Referenced by main().
search()
void Solver::search (State s, int depth) inline
Definition at line 981 of file main.cpp.
References activeThreads, applyDecision(), edges, State::edgeState, finalCheckAndStore(), findAll, isDefinitelyUnsolvable(), maxParallelDepth, maxThreads, State::pointDegree, State::pointUndecided, propagateConstraints(), quickValidityCheck(), search(), selectNextEdge(), stopAfterFirst, Edge::u, and Edge::v.
Referenced by run(), and search().
selectNextEdge()
int Solver::selectNextEdge (const State & s) const inline
Select next edge using smart heuristics (#11).
Prioritizes:
Forced moves (only one valid choice)
Edges that minimize branching factor
Edges adjacent to constrained cells
Definition at line 618 of file main.cpp.
References Edge::cellA, Edge::cellB, State::cellEdgeCount, State::cellUndecided, edges, State::edgeState, estimateBranches(), grid, State::pointDegree, State::pointUndecided, Edge::u, and Edge::v.
Referenced by search().
testEdgeDecision()
bool Solver::testEdgeDecision (const State & s, int edgeIdx, int val) const inline
Look-ahead pruning (#12) - Test if edge decision leads to valid state.
Performs 1-ply look-ahead to check if a decision will lead to solvable state. Returns false if the decision definitely leads to failure.
Definition at line 876 of file main.cpp.
References applyDecision(), edges, State::edgeState, and propagateConstraints().
Member Data Documentation
activeThreads
atomic<int> Solver::activeThreads {0}
Definition at line 186 of file main.cpp.
Referenced by search().
arena
unique_ptr<tbb::task_arena> Solver::arena
Definition at line 190 of file main.cpp.
Referenced by run().
cellEdges
vector<vector<int> > Solver::cellEdges
Definition at line 174 of file main.cpp.
Referenced by buildEdges(), initialState(), and propagateConstraints().
clueCells
vector<int> Solver::clueCells
Definition at line 176 of file main.cpp.
Referenced by buildEdges(), finalCheckAndStore(), isDefinitelyUnsolvable(), propagateConstraints(), and quickValidityCheck().
edges
vector<Edge> Solver::edges
Definition at line 169 of file main.cpp.
Referenced by applyDecision(), buildEdges(), estimateBranches(), finalCheckAndStore(), initialState(), propagateConstraints(), search(), selectNextEdge(), and testEdgeDecision().
findAll
bool Solver::findAll = false
Definition at line 178 of file main.cpp.
Referenced by isCanonicalSolution(), run(), and search().
grid
Grid Solver::grid
Definition at line 168 of file main.cpp.
Referenced by applyDecision(), buildEdges(), calculateOptimalParallelDepth(), finalCheckAndStore(), initialState(), isCanonicalSolution(), isDefinitelyUnsolvable(), main(), printSolution(), propagateConstraints(), run(), and selectNextEdge().
horizEdgeIndex
vector<int> Solver::horizEdgeIndex
Definition at line 172 of file main.cpp.
Referenced by buildEdges(), isCanonicalSolution(), and printSolution().
maxParallelDepth
int Solver::maxParallelDepth = 16
Definition at line 185 of file main.cpp.
Referenced by run(), and search().
maxThreads
int Solver::maxThreads = thread::hardware_concurrency() > 0 ? thread::hardware_concurrency() : 4
Definition at line 187 of file main.cpp.
Referenced by run(), and search().
numPoints
int Solver::numPoints = 0
Definition at line 170 of file main.cpp.
Referenced by buildEdges(), finalCheckAndStore(), initialState(), isDefinitelyUnsolvable(), propagateConstraints(), and quickValidityCheck().
pointEdges
vector<vector<int> > Solver::pointEdges
Definition at line 175 of file main.cpp.
Referenced by buildEdges(), initialState(), and propagateConstraints().
solMutex
mutex Solver::solMutex
Definition at line 181 of file main.cpp.
solutionCount
atomic<int> Solver::solutionCount {0}
Definition at line 183 of file main.cpp.
Referenced by run().
solutions
vector<Solution> Solver::solutions
Definition at line 182 of file main.cpp.
Referenced by printSolutions(), and run().
stopAfterFirst
atomic<bool> Solver::stopAfterFirst {false}
Definition at line 179 of file main.cpp.
Referenced by run(), and search().
tbbSolutions
tbb::concurrent_vector<Solution> Solver::tbbSolutions
Definition at line 191 of file main.cpp.
Referenced by run().
vertEdgeIndex
vector<int> Solver::vertEdgeIndex
Definition at line 173 of file main.cpp.
Referenced by buildEdges(), and printSolution().
The documentation for this struct was generated from the following files:
apps/slitherlink_cli/main.cpp
src/solver/Solver.cpp